// Generated by LiveScript 1.5.0
(function(){
  var myCtrl, app;
  myCtrl = function($scope, $route){
    var teachers;
    teachers = [
      {
        img: 'yi-ting.jpg',
        name: '蔡伊婷',
        xp: '諮詢經驗：2016~至今',
        times: ['週一下午2:00-4:00'],
        phone: '0919979804'
      }, {
        img: 'chia-jen.jpg',
        name: '朱佳仁',
        xp: '2011~至今',
        times: ['週四下午2:00-5:00'],
        phone: '0915165369'
      }
    ];
    angular.extend($scope, {
      teachers: teachers,
      $route: $route
    });
    angular.extend($scope, {
      checkRoute: function(n){
        return $route && $route.current && $route.current.templateUrl && $route.current.templateUrl.indexOf(n) > -1;
      }
    });
  };
  app = angular.module('contactApp', ['ngRoute']).controller('myCtrl', ['$scope', '$route', myCtrl]);
  app.config(function($routeProvider){
    return $routeProvider.when("/", {
      templateUrl: "contact-pages/main.html"
    }).when("/start", {
      templateUrl: "contact-pages/start.html"
    }).when("/plan", {
      templateUrl: "contact-pages/plan.html"
    }).when("/consult", {
      templateUrl: "contact-pages/consult.html"
    });
  });
}).call(this);
