// Generated by LiveScript 1.5.0
(function(){
  var myCtrl, app;
  myCtrl = function($scope, $route){
    var phones;
    phones = [{
      img: 'yi-ting.jpg',
      name: '蔡伊婷',
      topics: ['自學申請', '審議', '法規', '流程', '資源連結轉介'],
      xp: '諮詢經驗：2016~至今',
      times: ['週一下午2:00-4:00'],
      phone: '0919979804'
    }];
    angular.extend($scope, {
      phones: phones,
      $route: $route
    });
    angular.extend($scope, {
      checkRoute: function(n){
        return $route && $route.current && $route.current.templateUrl && $route.current.templateUrl.indexOf(n) > -1;
      }
    });
  };
  app = angular.module('contactApp', ['ngRoute']).controller('myCtrl', ['$scope', '$route', myCtrl]);
  app.config(function($routeProvider){
    return $routeProvider.when("/", {
      templateUrl: "contact-pages/main.html"
    }).when("/start", {
      templateUrl: "contact-pages/start.html"
    }).when("/plan", {
      templateUrl: "contact-pages/plan.html"
    }).when("/consult", {
      templateUrl: "contact-pages/consult.html"
    });
  });
}).call(this);
