// Generated by LiveScript 1.5.0
(function(){
  var myDonate, myDonaterCtrl;
  myDonate = function($http){
    var d;
    d = {};
    $http({
      method: 'GET',
      url: 'http://docs.google.com/feeds/download/spreadsheets/Export?key=1HSPIJk59KWwEDRcp6unYQ-SnfC0O0ELr0e8-gdH59Q4&exportFormat=csv&gid=0'
    }).then(function(res){
      console.log(res.data);
      d = data;
    }, function(err){
      console.log("ERR");
      console.log(err);
    });
    return d;
  };
  myDonaterCtrl = function($scope, $donater){
    var parseD;
    parseD = function(d){
      var objs;
      objs = d;
      return objs;
    };
    angular.extend({
      d: $scope[parseD($donater)]
    });
  };
  angular.module('donater', []).factory('$donater', ['$http', myDonate]).controller('myDonaterCtrl', ['$scope', '$donater', myDonaterCtrl]);
}).call(this);
